---
- include_tasks: cp4d-install-separate-cr-apply.yml
  when: 
  - (_current_cp4d_cartridge.state | default('installed')) == 'installed'
  - (_current_cp4d_cartridge.separate_install | default(False) | bool)