---
global_config:
  environment_name: sample
  cloud_platform: existing-ocp
  confirm_destroy: False

vault:
  vault_type: file-vault
  vault_authentication_type: none

openshift:  
- name: "{{ env_id }}"
  ocp_version: "4.10"
  cluster_name: "{{ env_id }}"
  domain_name: ocp-120000gh3t-tyhe.cloud.techzone.ibm.com
  openshift_storage:
  - storage_name: techzone
    storage_type: custom
    ocp_storage_class_file: ocs-storagecluster-cephfs
    ocp_storage_class_block: ocs-storagecluster-ceph-rbd

image_registry:
- name: demoreg
  registry_host_name: icr.io
  registry_namespace: sj-cpd

cp4i:
- project: cp4i
  openshift_cluster_name: "{{ env_id }}"
  cp4i_version: 2022.4.1-0
  accept_licenses: true
  #image_registry_name: demoreg
 
  instances:

  - type: platform-navigator
    state: installed

  - type: api-management
    state: removed

  - type: automation-assets
    state: removed

  - type: enterprise-gateway
    state: removed

  - type: event-endpoint-management
    state: removed

  - type: event-streams
    state: removed
  
  - type: high-speed-transfer-server
    state: removed

  - type: integration-dashboard
    state: removed

  - type: integration-design
    state: removed

  - type: integration-tracing
    state: removed

  - type: messaging
    state: removed