- name: Remove Project cloudbeaver
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: cloudbeaver
    wait: true
    wait_sleep: 15
    wait_timeout: 120
