- name: Create OpenLdap directory for generated files
  ansible.builtin.file:
    path: "{{ openldap_output_directory }}"
    state: directory
    mode: u+rwx

- name: Create Project
  ansible.builtin.include_role:
    name: common
    tasks_from: create-project
  vars:
    common_namespace_name: openldap
    common_output_directory: "{{ openldap_output_directory }}"

- name: Prepare yaml file for anyuid RoleBinding
  ansible.builtin.template:
    src: anyuid-scc-rolebinding.yaml.j2
    dest: "{{ openldap_output_directory }}/anyuid-scc-rolebinding.yaml"
    mode: u+rwx

- name: Add anyuid RoleBinding
  kubernetes.core.k8s:
    state: present
    force: false
    merge_type: merge
    src: "{{ openldap_output_directory }}/anyuid-scc-rolebinding.yaml"
    wait: true
    wait_sleep: 15
    wait_timeout: 15

- name: Add helm-openldap chart repo
  kubernetes.core.helm_repository:
    name: helm-openldap
    repo_url: "https://jp-gouin.github.io/helm-openldap/"

- name: Prepare yaml file for values of helm chart
  ansible.builtin.template:
    src: values.yaml.j2
    dest: "{{ openldap_output_directory }}/values.yaml"
    mode: u+rwx

- name: Deploy openldap chart using values files on target
  kubernetes.core.helm:
    name: openldap-openldap-stack-ha
    chart_ref: helm-openldap/openldap-stack-ha
    chart_version: "{{ openldap_chart_version }}"
    release_namespace: openldap
    values_files:
      - "{{ openldap_output_directory }}/values.yaml"

- name: Get OCP Apps Endpoint
  ansible.builtin.include_role:
    name: common
    tasks_from: apps-endpoint
  vars:
    common_output_to_var: "apps_endpoint_domain"
  when: apps_endpoint_domain is not defined

- name: Crete Edge Route
  ansible.builtin.include_role:
    name: common
    tasks_from: create-edge-route
  vars:
    common_namespace_name: openldap
    common_route_name: openldap-phpldapadmin
    common_service_name: openldap-openldap-stack-ha-phpldapadmin
    common_apps_endpoint_domain: "{{ apps_endpoint_domain }}"
    common_output_directory: "{{ openldap_output_directory }}"

- name: Wait for openldap-openldap-stack-ha-phpldapadmin Deployment to be Available
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition
  vars:
    common_api_version: apps/v1
    common_resource_kind: Deployment
    common_resource_name: openldap-openldap-stack-ha-phpldapadmin
    common_resource_namespace: openldap
    common_condition_name: Available
    common_retries: 60
    common_delay: 15

- name: Wait for openldap-openldap-stack-ha StatefulSet ready replicas
  ansible.builtin.include_role:
    name: common
    tasks_from: wait-resource-condition-generic
  vars:
    common_api_version: apps/v1
    common_resource_kind: StatefulSet
    common_resource_name: openldap-openldap-stack-ha
    common_resource_namespace: openldap
    common_condition_query: resources[*].status.readyReplicas
    common_condition_value: 1
    common_retries: 30
    common_delay: 120
