---
- set_fact:
    _cp4d_entitlement: "{{ current_cp4d_cluster.cp4d_entitlement | default('cpd-enterprise') }}"
    _cp4d_production_license: "{{ current_cp4d_cluster.cp4d_production_license | default('False') }}"

- debug:
    var: current_cp4d_cluster

- name: Generate apply-entitlement command
  template:
    src: apply-entitlement.j2
    dest: "{{ status_dir }}/cp4d/{{ current_cp4d_cluster.project }}-apply-entitlement.sh"
    mode: u=rwx

- name: Run apply-entitlement command
  shell: |
    {{ status_dir }}/cp4d/{{ current_cp4d_cluster.project }}-apply-entitlement.sh