- name: Remove Project mongo_express
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: mongo-express
    wait: true
    wait_sleep: 15
    wait_timeout: 120
