- name: Remove Project gitea
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: gitea
    wait: true
    wait_sleep: 15
    wait_timeout: 120
