- name: Remove Project postgresql
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: postgresql
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove RB postgresql-privileged
  kubernetes.core.k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: postgresql-privileged
    wait: true
    wait_sleep: 15
    wait_timeout: 120
