- name: Remove Project mongodb
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: mongodb
    namespace: mongodb
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove CRB mongodb-anyuid
  kubernetes.core.k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: mongodb-anyuid
    wait: true
    wait_sleep: 15
    wait_timeout: 120
