- name: Remove Project mail
  kubernetes.core.k8s:
    state: absent
    api_version: project.openshift.io/v1
    kind: Project
    name: mail
    wait: true
    wait_sleep: 15
    wait_timeout: 120

- name: Remove RB mail-privileged
  kubernetes.core.k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    name: mail-privileged
    wait: true
    wait_sleep: 15
    wait_timeout: 120
