- name: Remove usage Config Map
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: cp4ba-usage
    namespace: cloud-pak-deployer
    force: false
    wait: true
    wait_sleep: 15
    wait_timeout: 15
